version: "3"
services:
  db:
    image: postgres:13-alpine
    container_name: movies-db
    restart: on-failure
    env_file:
      - postgres.env
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/movies_database.ddl:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d movies_database"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  es:
    platform: linux/amd64
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.system_call_filter=false
      - bootstrap.memory_lock=true
      - network.host=localhost
    volumes:
      - esdata:/usr/share/elasticsearch/data
    # healthcheck:
    #   test: ["curl",]
    depends_on:
      db:
        condition: service_healthy

  state:
    container_name: state-saver
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - state:/data

volumes:
  esdata:
    driver: local
  db:
    driver: local
  state:
    driver: local
